name: DingRSS

on:
 push:
  branches:
    - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Send RSS
      env:
        DD_TOKEN: ${{ secrets.DING_TOKEN }}
        DD_SECRET: ${{ secrets.DING_SECRET }}
        
      run: |
        python main.py
    - name: Commit
      run: |
        git config --global user.email 1129159201@qq.com
        git config --global user.name rcy1314
        git add .
        git commit -m "Update caches" -a

